version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
<<<<<<< HEAD
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
=======
      interval: "weekly"
    labels:
      - "dependencies"
>>>>>>> 35d8cf69 (Initial commit)
